name: CI

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Format check
        run: dotnet format --verify-no-changes
      - name: Run analyzers
        run: dotnet build --configuration Release /warnaserror
      - name: Run tests
        run: dotnet test --configuration Release --no-build --verbosity normal
      - name: Check for vulnerable dependencies
        run: dotnet list package --vulnerable
