name: "Require PR checklist"
on: [pull_request]
jobs:
  checklist:
    runs-on: ubuntu-latest
    steps:
      - uses: technote-space/action-pr-checklist@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # Must exactly match the items in your template
          checklist: |
            - "[ ] My code follows the style guidelines of this project"
            - "[ ] I have performed a self-review of my own code"
            - "[ ] I have commented my code, particularly in hard-to-understand areas"
            - "[ ] I have made corresponding changes to the documentation"
            - "[ ] My changes generate no new warnings"
            - "[ ] I have added tests that prove my fix is effective or that my feature works"
            - "[ ] New and existing unit tests pass locally with my changes"



